export enum loginReturnedStatesEnum{
    EVERYTHINGCORRECT,
    WRONGPASSWORDOFEMAIL,
    NOTVERIEFIEDUSER,
    OTHERPROBLEM
}


export enum registerReturnedStatesEnum{
    EVERYTHINGCORRECT,
    EMAILISUSED,
    OTHERPROBLEM,
    TOSHORTPASSWORD,
    NICKISUSED,
    PASSWORDISNOTEQUELTOPASSCONFIRM
}